# edit below fields
appname: ArticleMaker

server:
  development:
    appurl: localhost
    port: 8000
database:
  development:
    dbdriver: mysql
    dbhost: localhost
    dbport: 3306
    dbname: articlemaker
    dbuser: username
    dbpassword: password
  testing:
    dbname: testdb
    dbdriver: sqlite
